name: Apply variant IDs

on:
  push:
    branches:
      - master
    paths:
      - 'variant_ids.json'
      - 'apply_variants.py'
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Apply variant IDs
      run: |
        python apply_variants.py
    - name: Check for changes
      id: check_changes
      run: |
        if git diff --quiet HEAD; then
          echo "No changes detected, exiting workflow"
          echo "nochanges=true" >> $GITHUB_OUTPUT
        fi
    - name: Get current date
      if: steps.check_changes.outputs.nochanges != 'true'
      id: get_date
      run: echo "date=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"
    - name: Create Pull Request
      if: steps.check_changes.outputs.nochanges != 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Apply variant IDs for ${{ steps.get_date.outputs.date }}
        branch: variant-ids-${{ steps.get_date.outputs.date }}
        delete-branch: true
        title: "Automated PR: Apply variant IDs"
        body: |
          Apply variant ID expansions for ${{ steps.get_date.outputs.date }}

          _Automatically generated by the GitHub Actions workflow._
        labels: |
          automated
          variant-ids
        assignees: |
          adamk33n3r
          t8or
